version: 2.1 

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2 # Use the AWS ECR orb in your config
  aws-ecs: circleci/aws-ecs@1.1.0 # Use the AWS ECS orb in your config

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          path: ./helloworld/.
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: '${CIRCLE_SHA1}' 
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run the deployment job once the build and push image job has completed
          family: 'superawesome_ecs'
          cluster-name: 'superawesome_ecs_cluster'
          container-image-name-updates: 'container=superawesome,tag=${CIRCLE_SHA1}'

