apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world
  namespace: hello-world
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: hello-world
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      target:
        apiVersion: extensions/v1beta1
        kind: Ingress
        name: hello-world
      targetValue: 200
      metricName: requests-per-second
